### ISSUE TITLE
conda version

### ISSUE THREAD

**Issue by weber8thomas** [jpquast/ggplate#14]
Hi! 

Thanks for this amazing tool! I'd like to know if any conda/bioconda version is planned, would facilitate integration into workflow managers (snakemake, nextflow, ...) 

Cheers, Thomas

**Comment by jpquast** [comment]
Hi @weber8thomas,
thanks for your question! I have actually never used conda/bioconda. I tried to look a bit into how I would submit packages there but it seems to at least mine would not be suited for bioconda since it does not depend on any package in bioconda or bioconductor. So they would recommend submitting it to conda-forge then.

What exactly is the advantage of having it in such a repository? Is it not possible to install it from CRAN for the workflow managers?

**Comment by jpquast** [comment]
I just created a conda-forge version of the package. 
You can find it here: https://anaconda.org/conda-forge/r-ggplate

**Comment by weber8thomas** [comment]
Amazing, thanks a lot @jpquast ! Will be really useful for me

> What exactly is the advantage of having it in such a repository? Is it not possible to install it from CRAN for the workflow managers?

When used in a nextflow/snakemake/other management system, it is super convenient to have a conda/container version to prevent custom installation when sharing the pipeline with different people :)
