### ISSUE TITLE
Plate background colour

### ISSUE THREAD

**Issue by jimbat76** [jpquast/ggplate#19]
Please select the "question" or "enhancement" label on the right depending on your issue.
I love this library and use it all the time, great work. Is is possible to change the colour of the plate background? I can't find a reference to this in the documentation and have tried a few attribute names such as `background_color` and things like that without luck.
It would be nice to have this feature (if it doesn't already exist) as sometimes the data stand out better when the background is not white.

Cheers!

![image](https://github.com/jpquast/ggplate/assets/32538659/802f6bfd-e08b-4218-8739-bc56d38b7486)

**Comment by jpquast** [comment]
Hi @jimbat76,
thanks for the question. There is no argument included in the function currently, but since it just produces a ggplot object, you can use `theme()` to style the plot.  Just use any background colour you like in the fill argument. But maybe it would also be worth it to add it as an argument in the future to make it easier to change.

``` r
library(ggplate)
#> 📊 Welcome to ggplate version 0.0.1! 📈
#>                             
#> 🖍 Have fun plotting your data! 💻
library(ggplot2)

# Change the background color of the panel
plate_plot(
  data = data_continuous_96,
  position = well,
  value = Value,
  plate_size = 96,
  plate_type = "square"
) +
  theme(panel.background = element_rect(fill = "#f7f5f5"))
```

![](https://i.imgur.com/LUmBgpE.png)

<sup>Created on 2024-01-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jimbat76** [comment]
Thanks @jpquast, your suggestion seems like a simple solution. Much appreciated, thanks again.
